# Generated by Django 6.1.1 on 2026-09-29 15:49, edited for pgvector setup.

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        # Enable the pgvector extension on the database (idempotent):
        # docker compose up then just works, no manual psql step.
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="DROP EXTENSION IF EXISTS vector;",
        ),
        migrations.AddField(
            model_name="chunk",
            name="embedding",
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
        # HNSW index on cosine distance for fast top-k retrieval.
        migrations.RunSQL(
            sql=(
                "CREATE INDEX IF NOT EXISTS chunk_embedding_hnsw "
                "ON documents_chunk USING hnsw (embedding vector_cosine_ops);"
            ),
            reverse_sql="DROP INDEX IF EXISTS chunk_embedding_hnsw;",
        ),
    ]
