# Generated by Django 6.1.1 on 2026-10-07 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def group_orphan_queries(apps, schema_editor):
    """Group pre-existing queries into one default conversation per user.

    Args:
        apps: The application registry providing historical models.
        schema_editor: The schema editor running the migration.

    Returns:
        None; existing queries are attached to a per-user conversation.
    """
    Conversation = apps.get_model("documents", "Conversation")
    Query = apps.get_model("documents", "Query")

    default_conversations = {}
    for query in Query.objects.filter(conversation__isnull=True).order_by("created_at"):
        key = query.user_id
        if key not in default_conversations:
            default_conversations[key] = Conversation.objects.create(
                owner_id=query.user_id,
                title="Historique importé",
            )
        query.conversation = default_conversations[key]
        query.save(update_fields=["conversation"])


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0003_document_owner_document_visibility_query_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                migrations.RunPython(group_orphan_queries, migrations.RunPython.noop),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="query",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="documents.conversation",
            ),
        ),
    ]
