# Generated by Django 6.1.1 on 2026-10-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_bootstrap_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="must_change_password",
            field=models.BooleanField(default=False),
        ),
    ]
