"""End-to-end scenarios: the full pipeline from upload to retrieval.

Each scenario runs the real stack pieces (API views, ingestion tasks,
chunking, retrieval, SSE formatting) with deterministic test doubles
for the ML models only, so the suite stays fast and offline-safe.
"""

import io
import json

import pytest
from django.core.files.uploadedfile import SimpleUploadedFile
from docx import Document as DocxDocument
from rest_framework.test import APIClient

from documents.models import Chunk, Document
from tests.fakes import FakeEmbeddingModel

pytestmark = pytest.mark.django_db

client = APIClient()

GUIDE_CONTENT = (
    "The Rag project uses PostgreSQL with the pgvector extension. "
    "Documents are chunked and embedded by a Celery worker. "
    "Retrieval searches the closest chunks with a cosine distance. "
    "Answers are generated by a local Qwen3 model."
)

CANNED_ANSWER = "Retrieval searches the closest chunks with a cosine distance."


def _make_pdf(name="guide.pdf"):
    """Build a minimal single-page PDF carrying real extractable text."""
    stream = f"BT /F1 12 Tf 72 720 Td ({GUIDE_CONTENT}) Tj ET".encode("latin-1")
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        (
            b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792]"
            b" /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>"
        ),
        b"<< /Length " + str(len(stream)).encode() + b" >>\nstream\n" + stream + b"\nendstream",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]
    buffer = io.BytesIO()
    buffer.write(b"%PDF-1.4\n")
    offsets = []
    for index, obj in enumerate(objects, start=1):
        offsets.append(buffer.tell())
        buffer.write(f"{index} 0 obj\n".encode() + obj + b"\nendobj\n")
    xref = buffer.tell()
    buffer.write(f"xref\n0 {len(objects) + 1}\n".encode())
    buffer.write(b"0000000000 65535 f \n")
    for offset in offsets:
        buffer.write(f"{offset:010d} 00000 n \n".encode())
    buffer.write(
        f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{xref}\n%%EOF".encode()
    )
    return SimpleUploadedFile(name, buffer.getvalue(), content_type="application/pdf")


def _make_docx(name="guide.docx"):
    """Build a minimal DOCX payload carrying the guide text."""
    document = DocxDocument()
    document.add_paragraph(GUIDE_CONTENT)
    buffer = io.BytesIO()
    document.save(buffer)
    buffer.seek(0)
    return SimpleUploadedFile(
        name,
        buffer.getvalue(),
        content_type=("application/vnd.openxmlformats-officedocument.wordprocessingml.document"),
    )


def _make_file(name):
    """Build a plain text or markdown upload payload."""
    return SimpleUploadedFile(name, GUIDE_CONTENT.encode("utf-8"), content_type="text/plain")


FORMAT_FILES = {
    "txt": lambda: _make_file("guide.txt"),
    "md": lambda: _make_file("guide.md"),
    "pdf": _make_pdf,
    "docx": _make_docx,
}


@pytest.fixture(autouse=True)
def eager_pipeline(settings, monkeypatch, tmp_path):
    """Run ingestion eagerly with deterministic ML doubles."""
    from rag_core import retriever as retriever_module

    settings.CELERY_TASK_ALWAYS_EAGER = True
    settings.CELERY_TASK_EAGER_PROPAGATES = True
    monkeypatch.setattr("ingestion.embedding.get_embedding_model", lambda: FakeEmbeddingModel())
    monkeypatch.setattr(
        "queries.views.generate_answer",
        lambda question, chunks: ("", CANNED_ANSWER),
    )
    monkeypatch.setenv("UPLOAD_DIR", str(tmp_path / "uploads"))
    monkeypatch.setattr(
        retriever_module.embedding_module,
        "get_embedding_model",
        lambda: FakeEmbeddingModel(),
    )
    yield


def _parse_sse(response):
    """Parse a streaming response into (tokens, sources_or_none, error)."""
    tokens = []
    sources = None
    error = None
    for part in response.streaming_content:
        text = part.decode("utf-8")
        for block in text.split("\n\n"):
            lines = block.strip().splitlines()
            event = next((line[6:].strip() for line in lines if line.startswith("event:")), None)
            data = next((line[5:].strip() for line in lines if line.startswith("data:")), None)
            if event == "token":
                tokens.append(json.loads(data)["text"])
            elif event == "sources":
                sources = json.loads(data)
            elif event == "error":
                error = json.loads(data)
    return tokens, sources, error


def _upload(file_payload):
    """Upload a document and wait for eager ingestion to finish."""
    response = client.post("/api/documents/", {"file": file_payload}, format="multipart")
    assert response.status_code == 202
    document_id = response.json()["id"]
    document = Document.objects.get(pk=document_id)
    assert document.status == "indexed"
    return document


def test_upload_to_indexed_pipeline_for_every_format():
    """Upload → ingestion → indexed, for the four accepted formats."""
    for make_file in FORMAT_FILES.values():
        document = _upload(make_file())
        assert document.chunks.count() >= 1


def test_question_streams_answer_citing_the_uploaded_document():
    """Question → streamed answer with sources from the document."""
    document = _upload(_make_file("guide.txt"))
    response = client.post("/api/query/", {"question": "How does retrieval work?"}, format="json")
    assert response.status_code == 200
    assert response["Content-Type"].startswith("text/event-stream")
    tokens, sources, error = _parse_sse(response)
    assert error is None
    assert "".join(tokens).strip()
    assert sources is not None
    source_document_ids = {source["document"]["id"] for source in sources["sources"]}
    assert source_document_ids == {document.pk}


def test_deletion_removes_document_and_future_retrieval():
    """Deletion → document and chunks gone, retrieval returns nothing."""
    document = _upload(_make_file("guide.txt"))
    assert Chunk.objects.filter(document=document).exists()

    response = client.delete(f"/api/documents/{document.pk}/")
    assert response.status_code in (200, 204)
    assert not Document.objects.filter(pk=document.pk).exists()
    assert not Chunk.objects.filter(document_id=document.pk).exists()

    query = client.post("/api/query/", {"question": "How does retrieval work?"}, format="json")
    _, sources, _ = _parse_sse(query)
    assert sources is not None
    assert sources["sources"] == []


def test_reupload_replaces_chunks_without_duplicates():
    """Re-upload of the same file → chunks replaced, no duplicates."""
    first = _upload(_make_file("guide.txt"))
    second = _upload(_make_file("guide.txt"))
    assert second.pk != first.pk
    assert Document.objects.count() == 2
    chunk_count = Chunk.objects.count()
    assert chunk_count == first.chunks.count() + second.chunks.count()
    assert Chunk.objects.values("document").distinct().count() == 2
